### ISSUE TITLE
Cisco: command not found

### ISSUE THREAD

**Issue by stensmir** [augustplaninsek/vpn-cisco-anyconnect#1]
Hi! Thank you for script! But i have problem on run script: 
vpn.sh: line 11: Cisco: command not found 
Cisco version 4.9.06037, Mac OS X 12.1, m1 max
I change only credential in file. Any help, please.
Best regards

UPD: if I run  printf "y\n${USERNAME}\n${PASSWORD}" | /opt/cisco/anyconnect/bin/vpn -s connect ${HOST}
I see:
VPN is disconnected. Connecting...
Cisco AnyConnect Secure Mobility Client (version 4.9.06037) .

Copyright (c) 2004 - 2021 Cisco Systems, Inc.  All Rights Reserved.

  >> state: Disconnected
  >> state: Disconnected
  >> notice: Ready to connect.
  >> registered with local VPN subsystem.
  >> contacting host (*****) for login information...
  >> state: Disconnected
  >> error: Connect not available. Another AnyConnect application is running
or this functionality was not requested by this application.
VPN> 

But no any running client

**Comment by stensmir** [comment]
Problem solved! I use https://github.com/JohnSundell/ShellOut and this work. Thx!

**Comment by eliahuhorwitz** [comment]
@stensmir Could you please elaborate on how did you use ShellOut? I have the same error

**Comment by stensmir** [comment]
Hi! Yes, go to my repo [VPNAnyConnect](https://github.com/stensmir/VPNAnyConnect)
